fix checksum test, error if dest exists and do not cleanup source

diff --git a/src/smdba/smdba-pgarchive b/src/smdba/smdba-pgarchive
--- a/src/smdba/smdba-pgarchive
+++ b/src/smdba/smdba-pgarchive
@@ -40,8 +40,9 @@ fi
 
 if [ -f "$DESTINATION" ]; then
     # file already exist in the backup
-    # exit without error
-    exit 0
+    # exit with error
+    echo "File already exists: $DESTINATION" >&2
+    exit 1
 fi
 
 if ! cp --preserve=all $SOURCE $DESTINATION; then
@@ -49,18 +50,14 @@ if ! cp --preserve=all $SOURCE $DESTINATION; then
     exit 1
 fi
 
-FILENAME=`basename $SOURCE`
-SHA1SOURCE=`sha1sum $SOURCE`
-SHA1DEST=`sha1sum $DESTINATION/$FILENAME`
+SHA1SOURCE=`sha1sum $SOURCE | awk '{print $1}'`
+SHA1DEST=`sha1sum $DESTINATION | awk '{print $1}'`
 
-if [ "$SHA1SOURCE" = "$SHA1DEST" ]; then
-    echo "Checksum error $SHA1DEST: $SHA1SOURCE vs. $SHA1DEST" >&2
+if [ "$SHA1SOURCE" != "$SHA1DEST" ]; then
+    echo "Checksum error $DESTINATION: $SHA1SOURCE vs. $SHA1DEST" >&2
     # remove broken backup file
-    rm -f $SHA1DEST
+    rm -f $DESTINATION
     exit 1
 fi
-
-# remove archive log
-rm -f $SOURCE
 
 exit 0
